Desktop/electro-monitoring-sample/MyApp.Server/Models/ViewModels/ElectrometerViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyApp.Server.Models.ViewModels
{
  public class ConciseElectrometerViewModel
  {
    public int Id { get; set; }

    public string Name { get; set; }
    
    public string Model { get; set; }
  }

  public class DetailedElectrometerViewModel
  {
    public int Id { get; set; }

    public string Model { get; set; }
    
    public string Name { get; set; }

    public string DeviceIp { get; set; }

    public int DevicePort { get; set; }

    public int DeviceId { get; set; }

    public string ConnectionType { get; set; }
  }

  public class ElectrometerModel
  {
    public string Name { get; set; }
  }
  
  public class ElectrometerConnectionType
  {
    public string Name { get; set; }
  }
}

Desktop/electro-monitoring-sample/MyApp.Server/Models/ViewModels/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace MyApp.Server.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

Desktop/electro-monitoring-sample/MyApp.Server/Controllers/ElectrometersController.cs
namespace MyApp.Server.Controllers
{
  using AutoMapper;
  using Models.BagViewModels;
  using Models.BindingModels;
  using Models.ViewModels;
  using MyApp.Data.UnitOfWork;
  using MyApp.Models;
  using System;
  using System.Collections.Generic;
  using System.Linq;
  using System.Web.Mvc;

  public class ElectrometersController : BaseController
  {
    public ElectrometersController(IMyAppData data) : base(data) { }
    
    [HttpGet]
    public ActionResult Add()
    {
      LoadModelsAndConnTypesInView();

      return View();
    }

    [HttpPost]
    public ActionResult Add(AddElectroBindingModel BindingModel)
    {
      if (!this.ModelState.IsValid)
      {
        LoadModelsAndConnTypesInView();
        return View(BindingModel);
      }

      try
      {
        Electrometer newElectro = new Electrometer
        {
          Name = BindingModel.Name,
          Model = BindingModel.Model,
          IsStopped = false,
          ConnectionType = BindingModel.ConnectionType,
          DeviceId = BindingModel.DeviceId,
          DeviceIp = BindingModel.DeviceIp,
          DevicePort = BindingModel.DevicePort
        };
        this.Data.Electrometers.Add(newElectro);
        this.Data.SaveChanges();

        return RedirectToAction("index", "home", null);
      }
      catch(Exception ex)
      {
        ModelState.AddModelError("", "An error occured");
        return View(BindingModel);
      }
    }

    [HttpGet]
    public ActionResult Manage()
    {
      var electros = this.Data.Electrometers.All();

      return View(Mapper.Map<IEnumerable<ConciseElectrometerViewModel>>(electros));
    }

    [HttpPost]
    public JsonResult Delete(string id)
    {
      Electrometer electro = this.Data.Electrometers.Find(int.Parse(id));
      try
      {
        this.Data.Electrometers.Remove(electro);
        this.Data.SaveChanges();
        return Json(new
        {
          success = true
        });
      }
      catch(Exception ex)
      {
        return Json(new
        {
          success = false,
          message = ex.Message
        });
      }
    }

    [HttpGet]
    public ActionResult Edit(int id)
    {
      var electro = this.Data.Electrometers.Find(id);

      LoadModelsAndConnTypesInView();

      return View(Mapper.Map<DetailedElectrometerViewModel>(electro));
    }

    [HttpPost]
    public ActionResult Edit(int id, DetailedElectrometerViewModel BindingModel)
    {
      Electrometer electro = this.Data.Electrometers.Find(id);
      try
      {
        electro.ConnectionType = BindingModel.ConnectionType;
        electro.Model = BindingModel.Model;
        electro.DeviceId = BindingModel.DeviceId;
        electro.DeviceIp = BindingModel.DeviceIp;
        electro.DevicePort = BindingModel.DevicePort;
        electro.Name = BindingModel.Name;
        this.Data.Electrometers.Update(electro);
        this.Data.SaveChanges();

        return this.RedirectToAction("manage", "electrometers", null);
      }      
      catch(Exception ex)
      {
        return this.View(BindingModel);
      }
      return View(BindingModel);
    }

    private void LoadModelsAndConnTypesInView()
    {
      var models = this.Data.Electrometers.All().GroupBy(el => el.Model, (key, g) => g.FirstOrDefault());
      var connTypes = this.Data.Electrometers.All().GroupBy(el => el.ConnectionType, (key, g) => g.FirstOrDefault());

      this.ViewBag.Models = Mapper.Map<IEnumerable<ElectrometerModel>>(models);
      this.ViewBag.ConnectionTypes = Mapper.Map<IEnumerable<ElectrometerConnectionType>>(connTypes);
    }
  }
}

Desktop/electro-monitoring-sample/MyApp.Server/Controllers/ManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using MyApp.Server.Models;

namespace MyApp.Server.Controllers
{
    [Authorize]
    public class ManageController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageController()
        {
        }

        public ManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePhoneNumberAsync(User.Identity.GetUserId(), model.PhoneNumber, model.Code);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.AddPhoneSuccess });
            }
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "Failed to verify phone");
            return View(model);
        }

        //
        // POST: /Manage/RemovePhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemovePhoneNumber()
        {
            var result = await UserManager.SetPhoneNumberAsync(User.Identity.GetUserId(), null);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.Error });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", new { Message = ManageMessageId.RemovePhoneSuccess });
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        //
        // GET: /Manage/SetPassword
        public ActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await UserManager.AddPasswordAsync(User.Identity.GetUserId(), model.NewPassword);
                if (result.Succeeded)
                {
                    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    if (user != null)
                    {

Desktop/electro-monitoring-sample/MyApp.Server/Views/Electrometers/Add.cshtml
@model MyApp.Server.Models.BindingModels.AddElectroBindingModel
@{ this.ViewBag.Title = "Electometer add"; }

<br><br>
@using (Html.BeginForm("Add", "Electrometers", FormMethod.Post, new { @class = "form-horizontal col-md-8 col-md-offset-2" }))
{
  @Html.AntiForgeryToken()
  <fieldset>
    <legend>Add electrometer form</legend>
    @Html.ValidationSummary()
    <div class="form-group">
      <label class="col-lg-2 control-label">Room </label>
      <div class="col-lg-10">
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @*<input class="form-control" id="Name" name="Name" placeholder="Room name" type="text" value="">*@
        @Html.ValidationMessageFor(model => model.Name)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DeviceIp, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.TextBoxFor(model => model.DeviceIp, new { @class = "form-control" })
        @*<input class="form-control" id="DeviceIp" name="DeviceIp" placeholder="Device IP" type="text" value="@Model.DeviceIp">*@
        @Html.ValidationMessageFor(model => model.DeviceIp)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DevicePort, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.TextBoxFor(model => model.DevicePort, new { @class = "form-control" })
        @*<input class="form-control" id="DevicePort" name="DevicePort" placeholder="Device port" type="text" value="@Model.DevicePort">*@
        @Html.ValidationMessageFor(model => model.DevicePort)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DeviceId, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.TextBoxFor(model => model.DeviceId, new { @class = "form-control" })
        @*<input class="form-control" id="DeviceId" name="DeviceId" placeholder="Device ID" type="text" value="@Model.DeviceId">*@
        @Html.ValidationMessageFor(model => model.DeviceId)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.Model, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @foreach (var ElectroModel in this.ViewBag.Models as IEnumerable<ElectrometerModel>)
        {
          <div class="radio">
            <label>
              <input name="Model" id="Model" value="@ElectroModel.Name" checked="" type="radio">
              @ElectroModel.Name.Replace("Schneider.", "")
            </label>
          </div>
        }
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.ConnectionType, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @foreach (var ElectroConnType in this.ViewBag.ConnectionTypes as IEnumerable<ElectrometerConnectionType>)
        {
          <div class="radio">
            <label>
              <input name="ConnectionType" id="ConnectionType" value="@ElectroConnType.Name" checked="" type="radio">
              @ElectroConnType.Name.Replace("_", " ")
            </label>
          </div>
        }
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="reset" class="btn btn-default">Cancel</button>
        <input type="submit" value="Submit" class="btn btn-primary">
      </div>
    </div>
  </fieldset>
}

Desktop/electro-monitoring-sample/MyApp.Server/Views/Electrometers/Edit.cshtml
@model DetailedElectrometerViewModel
@{
    ViewBag.Title = "Edit electrometer";
}

<br><br>
@using (Html.BeginForm("Edit", "Electrometers", FormMethod.Post, new { @class = "form-horizontal col-md-8 col-md-offset-2" }))
{
  @Html.AntiForgeryToken()
  <fieldset>
    <legend>Add electrometer form</legend>
    @Html.ValidationSummary()
    <div class="form-group">
      <label class="col-lg-2 control-label">Room </label>
      <div class="col-lg-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @*<input class="form-control" id="Name" name="Name" placeholder="Room name" type="text" value="">*@
        @Html.ValidationMessageFor(model => model.Name)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DeviceIp, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.EditorFor(model => model.DeviceIp, new { htmlAttributes = new { @class = "form-control" } })
        @*<input class="form-control" id="DeviceIp" name="DeviceIp" placeholder="Device IP" type="text" value="@Model.DeviceIp">*@
        @Html.ValidationMessageFor(model => model.DeviceIp)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DevicePort, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.EditorFor(model => model.DevicePort, new { htmlAttributes = new { @class = "form-control" } })
        @*<input class="form-control" id="DevicePort" name="DevicePort" placeholder="Device port" type="text" value="@Model.DevicePort">*@
        @Html.ValidationMessageFor(model => model.DevicePort)
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.DeviceId, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @Html.EditorFor(model => model.DeviceId, new { htmlAttributes = new { @class = "form-control" } })
        @*<input class="form-control" id="DeviceId" name="DeviceId" placeholder="Device ID" type="text" value="@Model.DeviceId">*@
        @Html.ValidationMessageFor(model => model.DeviceId)
      </div>
    </div>
    <div class="form-group" id="model-panel" data-model="@Model.Model">
      @Html.LabelFor(model => model.Model, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @foreach (var ElectroModel in this.ViewBag.Models as IEnumerable<ElectrometerModel>)
        {
          <div class="radio">
            <label>
              <input name="Model" id="Model" value="@ElectroModel.Name" checked="" type="radio">              
              @ElectroModel.Name.Replace("Schneider.", "")
            </label>
          </div>
        }
      </div>
    </div>
    <div class="form-group">
      @Html.LabelFor(model => model.ConnectionType, new { @class = "col-lg-2 control-label" })
      <div class="col-lg-10">
        @foreach (var ElectroConnType in this.ViewBag.ConnectionTypes as IEnumerable<ElectrometerConnectionType>)
        {
          <div class="radio">
            <label>
              <input name="ConnectionType" id="ConnectionType" value="@ElectroConnType.Name" checked="" type="radio">
              @ElectroConnType.Name.Replace("_", " ")
            </label>
          </div>
        }
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <a class="btn btn-default" href="/electrometers/manage">Cancel</a>
        <input type="submit" value="Submit" class="btn btn-primary">
      </div>
    </div>
  </fieldset>
}

@section scripts {
  <script src="~/js/electrometer-edit.js"></script>  
}

Desktop/electro-monitoring-sample/MyApp.Server/Views/Electrometers/Manage.cshtml
@model IEnumerable<ConciseElectrometerViewModel>
@{
    ViewBag.Title = "Delete";
}
@section libs {
  @Scripts.Render("~/bundles/jconfirm")
  @Styles.Render("~/bundles/jconfirm-css")
}

<h2>Delete or edit electrometers</h2>
<hr />

<table class="table table-striped electrometers-table table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Room name</th>
      <th>Model</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  @foreach(var electro in Model)
  {
    <tr class="electrometer" id="electrometer-@electro.Id">
      <td>@electro.Id</td>
      <td>@electro.Name</td>
      <td>@electro.Model</td>
      <td>
        <a class="btn btn-primary" href="/electrometers/edit/@electro.Id">Edit</a>
        <a class="btn btn-danger electrometer-delete" data-id="@electro.Id" href="#">Delete</a>
      </td>
    </tr>
  }
  </tbody>
</table> 

@section scripts {
  <script src="~/js/electrometer-delete.js"></script>  
}